<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Home</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
      	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

        <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

		<script src="https://cdn.rawgit.com/JDMcKinstry/JavaScriptDateFormat/master/Date.format.min.js"></script> 
    </head>
    <body>
		<p>Select birthday wll happen in x days, from today</p>
		<p>
			<select id="dayDropDown">
  				<option value="all">all</option>
  				<option value="30">30 days</option>
  				<option value="60">60 days</option>
  				<option value="90">90 days</option>
			</select>
		</p>

        <?php if (isset($userArr)) : ?>
			<div class="table-responsive">
				<table class="table" id="dayTable">
  					<thead>
    					<tr>
      						<th scope="col">#</th>
      						<th scope="col">First</th>
      						<th scope="col">Last</th>
      						<th scope="col">Birthday</th>
    					</tr>
  					</thead>
  					<tbody>
						<?php foreach($userArr as $t): ?>
						<tr>
      						<td><?php echo $t['id'] ?></td>	
      						<td><?php echo $t['firstName'] ?></td>
      						<td><?php echo $t['lastName'] ?></td>
      						<td><?php echo $t['birthday'] ?></td>
    					</tr>
						<?php endforeach; ?>
  					</tbody>
				</table>					
			</div>
        <?php else: ?>
        <?php endif; ?>
    </body>
	
	<script type="text/javascript">
		$( document ).ready(function() {
			$('#dayDropDown').change(function(){
     			var dayNum = $('#dayDropDown').find(":selected").val();
				var currDate = new Date();
				currDate = currDate.format('Y-m-d');

				var url;
				if(dayNum == 'all') {
					url = '/api/users';
				} else { 
					url = '/api/users/' + currDate + '/' + dayNum;
				}
				var items = [];
			
     			$.ajax({
         			url: url,
         			cache: false,
         			type: 'GET',
         			success: function(data){ 
            			//console.log(data);
						$("#dayTable tbody").remove();

						$.each(data, function (key, item) {
                        	items.push(buildItemRow(item));
                    	});
				
                    	$('<tbody/>', {
                        	html: items.join('')
                    	}).appendTo('thead');
					}
         		});
    		});			
		});

		function buildItemRow(item) {
			var html = 
				'<tr>' +
					'<td>' + item.id + '</td>' +  
					'<td>' + item.firstName + '</td>' +				
					'<td>' + item.lastName + '</td>' +
					'<td>' + item.birthday + '</td>' +	
				'</tr>';

			return html;	
		}
	</script>
</html>
